### ISSUE TITLE
Automation: Job `01-processForm.js` fails for TT form

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#161]
## Describe the bug
WCS is working with a new partner Trillion Trees that also wants to use the automation solution for their Kobo forms. We therefore setup the automation jobs in a new OpenFn project, but they're failing with the first test we're running with a new TT Kobo form. 

## To Reproduce
Form is found in Kobo... but OpenFn is unable to process and fails with `TypeError`: 
https://www.openfn.org/projects/p5qvqx/runs/0617ab75-9ed5-7d6f-807c-863a4ecc522c

### expression.js
01-processForm.js
A2 on prod: https://www.openfn.org/projects/p5qvqx/jobs/jyk5za

### state.json
NOTE: This is a different OpenFn project `Trillion Trees` with a different Kobo acct
See LP for `Trillion Trees Kobo`
This input was run through A1 job `00`: https://www.openfn.org/projects/p5qvqx/jobs/jvq5nj
```
      {
       uid: 'a587nJHzyBYATXi3Nb2yc7',
       p1: 'TT',
       p2: '',
       tableId: 'SiteRegistration'
       },
```

## Expected behavior
Automation solution fails to process forms to generate SQL output and Job.

**Comment by aleksa-krolls** [comment]
@lakhassane please prioritize in the AM when back along. 

@ritazagoni pls help with testing in the TT project when this is ready.

**Comment by lakhassane** [comment]
@aleksa-krolls the issue with `processForms` is solved: https://www.openfn.org/projects/p5qvqx/runs/061811bb-c113-7532-9d6e-39ec1b42b90c

However, I see the other flow jobs are all failing with 
- 500 status code: https://www.openfn.org/projects/p5qvqx/runs/061811bc-27a0-724a-8674-424ec30a7d68
- create table permission denied: https://www.openfn.org/projects/p5qvqx/runs/061811bc-2877-7b0d-956f-2558186c7f03 AND https://www.openfn.org/projects/p5qvqx/runs/061811bc-2929-7e41-b313-bbf8f0b5f22c

**Comment by lakhassane** [comment]
@aleksa-krolls the issue with `processForms` is solved: https://www.openfn.org/projects/p5qvqx/runs/061811bb-c113-7532-9d6e-39ec1b42b90c

However, I see the other flow jobs are all failing with 
- 500 status code: https://www.openfn.org/projects/p5qvqx/runs/061811bc-27a0-724a-8674-424ec30a7d68
- create table permission denied: https://www.openfn.org/projects/p5qvqx/runs/061811bc-2877-7b0d-956f-2558186c7f03 AND https://www.openfn.org/projects/p5qvqx/runs/061811bc-2929-7e41-b313-bbf8f0b5f22c

**Comment by aleksa-krolls** [comment]
@taylordowns2000 issue blocked and these 2 runs (see Mamadou's comment) fail because of access issues. See my Slack thread where we need your assistance: https://openfn.slack.com/archives/G2LJCFFDW/p1635856136031600?thread_ts=1635851478.016300&cid=G2LJCFFDW

**Comment by aleksa-krolls** [comment]
@lakhassane See my Slack thread. Automation solution is failing with `422`: https://openfn.slack.com/archives/G2LJCFFDW/p1635876717085200?thread_ts=1635851478.016300&cid=G2LJCFFDW

Also please note the security question I flagged re: run logs for this openfn adaptor.

**Comment by lakhassane** [comment]
@aleksa-krolls both projects working fine using the integer project_id. We were having a failure because of API changes where we no longer used hash ids to insert jobs.

TT: https://openfn.org/projects/p5qvqx/runs/0618264b-a5fe-7dc6-b887-e2545bda1d5e

WCS: https://openfn.org/projects/p5x4g4/runs/06182637-85a1-7e3a-b4a7-c1f89e888d51

**Comment by aleksa-krolls** [comment]
Ok, great. So what will we use going forward... integers or hash ids? 

Then I'm still not able to successfully run the full automation for the TT form: 
1. A3 sql failing: https://openfn.org/projects/p5qvqx/runs/06182662-7d1a-7331-b805-d7faa224423c
2. A5 dictionary failing: https://openfn.org/projects/p5qvqx/runs/06182662-7dd2-7309-a9a0-bbfe44904c77
(For this, I want to write SQL and not make any DB changes because I don't have permissions to create tables... we don't even have this TT credential, WCS owns it)

For testing, you can use the `wcs test mssql db`

**Comment by taylordowns2000** [comment]
The credential should use an integer `projectId` (until further notice... this is _very unlikely_ to change, but if it does it we will be prepared and will need to change these credentials.)

Inside the job itself, there's nowhere else that is specifying an `id`. Instead, @lakhassane is _using_ the `id` values he's getting back from the various APIs in later payloads. Because of this, they won't need changing going forward no-matter how the API changes, because we can all but guarantee that the API will always return some sort of valid `id` and if you just use what they gave you, you should be OK.
